name: tevi_data_team_dbt
version: '1.0'
config-version: 2

profile: tevi_data_team_dbt

target-path: target
clean-targets:
  - target
  - dbt_modules

macro-paths: ["macros"]

model-paths: ["models"]

models:
  tevi_data_team_dbt:
    bqr:
      +materialized: table
      +tags: ['bqr']
      +description: "Bigquery table, truncate table after query is finished"
      +partition_by:
        field: "date_key"
        data_type: "date"
    bqr_incremental:
      +materialized: incremental
      +tags: ['bqr_incremental']
      +description: "Bigquery incremental table, unique key is required for merge, if not provided, it only appends new rows"
      +partition_by:
        field: "date_key"
        data_type: "date"
    bqr_ephemeral:
      +materialized: ephemeral
      +tags: ['bqr_ephemeral']
      +description: "Bigquery ephemeral table, no data is stored, basically CTE"
    incremental_optimized:
      +materialized: incremental
      +tag: ['clh_incremental_optimized']
      +description: "Incremental table instanctly optimized after query is finished, duplicates should not persist"
      +post-hook: "OPTIMIZE TABLE {{ this }} FINAL"
      +partition_by: "toStartOfMonth(created_at)"
      +order_by: "created_at"
    normal:
      +materialized: table
      +tag: ['clh']
      +description: "Normal table"
      +partition_by: "toStartOfMonth(created_at)"
      +order_by: "created_at"
    incremental:
      +materialized: incremental
      +tag: ['clh_incremental']
      +description: "Incremental table to be optimized by clickhouse, duplicates are allowed until optimization at random time"
      +partition_by: "toStartOfMonth(created_at)"
      +order_by: "created_at"
    view:
      +materialized: view
      +tag: ['clh_view']
      +description: "View table, no data is stored, none physical table"
    ephemeral:
      +materialized: ephemeral
      +tag: ['clh_ephemeral']
      +description: "Ephemeral table, no data is stored, basically CTE"