tevi_data_team_dbt:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: "{{ env_var('CLICKHOUSE_PORT') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      schema: tevi_data_team
      secure: false

    bigquery:
      type: bigquery
      method: service-account
      project: "{{ env_var('BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET') }}"
      keyfile: "{{ env_var('BIGQUERY_KEYFILE') }}"
      threads: 1 # default is 1